### ISSUE TITLE
The website is down and it's usecase

### ISSUE THREAD

**Issue by gajeshbhat** [canonical-web-and-design/feedinghopeandheroes.org#10]
The website is down and cannot be reached. Is the website still in use or relevant? If not, the repo must be archived.

<img width="1437" alt="Screenshot 2023-06-14 at 9 36 58 PM" src="https://github.com/canonical/feedourfrontline.org/assets/16153045/87616136-13a4-4ba0-be09-a4e0ae88e0fd">

**Comment by anthonydillon** [comment]
Hi @gajeshbhat thanks for taking the time to report this issue to us. This is no longer an active project or site we are maintaining. I will archive this project. Thank you.
